#!/bin/sh
# Apply GitHub PRs with 'git-am'. This takes the pull-request ID as its first
# argument, each subsequent argument is passed to the 'git am' command.

argv0="$(basename "$0")"

if [ -z "$1" ]; then
	>&2 printf "usage: %s <pull-request id> [flags...]\n" "$argv0"
	exit 1
fi

for b in awk curl git; do
	if ! hash "$b"; then
		>&2 printf "%s: requires %s\n" "$argv0" "$b"
		exit 1
	fi
done

remote=$(git config --get remote.http.url)

if [ "$remote" = "" ]; then
	>&2 printf "%s: remote.http.url not set\n" "$argv0"
	exit 1
fi

patch=$(mktemp)

trap "rm -f $patch" EXIT

if ! curl -Lsf "$remote"/pull/"$1".patch > "$patch"; then
	>&2 printf "%s: failed to curl patch url\n" "$argv0"
	exit 1
fi

shift 1

git am "$@" < "$patch"
