#!/usr/bin/env python
import random
import sys

def randline(fname):
	f = open(fname, "r")

	lines = f.readlines()

	f.close()

	line = lines[random.randint(0, len(lines) - 1)]

	return line[:len(line)-1]

def main():
	try:
		adj = randline("/usr/share/words/adjs")
		noun = randline("/usr/share/words/nouns")
	except Exception as e:
		sys.stderr.write("{0}\n".format(e))
		sys.exit(1)

	sys.stdout.write("{0}-{1}\n".format(adj, noun))

if __name__ == "__main__":
	main()
