#!/bin/sh

# jqed - Shell wrapper around jq for editing JSON files in place.

FILTER=""
FILE=""
OPTS=""

usage() {
	echo "usage: jqed <jq filter> <file> <jq options>"
	exit 0
}

if [ -t 0 ]; then
	FILTER="$1"
	FILE="$2"
	OPTS="${@:3}"

	if [ -z "$FILTER" ]; then
		usage
	fi

	if [ -z "$FILE" ]; then
		usage
	fi
else
	read FILTER
	FILE="$1"
	OPTS="${@:2}"

	if [ -z "$FILE" ]; then
		usage
	fi
fi

TMP=$(mktemp)
OUT=$(mktemp)

cp $FILE $TMP

jq "$FILTER" $TMP $OPTS > $OUT

if [ $? -eq 0 ]; then
	diff $TMP $OUT > /dev/null

	if [ $? -gt 0 ]; then
		cp $OUT $FILE
	fi
fi

rm $TMP $OUT
