#!/bin/sh

[ $# -eq 0 ] && {
	>&2 printf "usage: %s <image>\n" "$(basename "$0")"
	exit 1
}

file="$1"
shift 1

set -x

qemu-system-x86_64 -daemonize \
	-enable-kvm \
	-sdl \
	-m 8192 \
	-drive file="$file",media=disk,if=virtio \
	-net nic,model=virtio \
	-smp 2 \
	-net user,hostfwd=tcp::2222-:22 \
	"$@"
