#!/bin/sh

[ $# -eq 0 ] && {
	>&2 printf "usage: %s <image>\n" "$(basename "$0")"
	exit 1
}

file="$1"
shift 1

set -x

qemu-system-x86_64 -daemonize \
	-enable-kvm \
	-display sdl \
	-m 8192 \
	-drive file="$file",media=disk,if=virtio \
	-net nic,model=virtio \
	-net user,hostfwd=tcp:127.0.0.1:2222-:22 \
	-smp 2 \
	"$@"
