#!/bin/sh

# rand - Generate a random alphanumeric string of the given length

LEN="32"

if [ ! -z "$1" ]; then
	LEN="$1"
fi

rand="$(tr -dc 'a-zA-Z0-9' < /dev/urandom | fold -w "$LEN" | head -n 1)"

if [ -t 1 ]; then
	echo "$rand"
else
	echo -n "$rand"
fi
